### ISSUE TITLE
Use integers for index of sudoku cells

### ISSUE THREAD

**Issue by lk16** [sk1u/doku#1]
https://github.com/sk1u/doku/blob/08fe251be8c3971dc867fa9cbfd69250fd8c9fc9/internal/doku.go#L15

Why use indexes such as `A1`? You don't need a separate type `index` for this.
I suggest to use integers instead, starting from `0`, going up to `80`.
That way you can access fields using `grid[9*y+x]`. Also, you can change the type of grid to `[]value` with length 81 and similarly for other fields of `Sudoku`.

**Comment by sk1u** [comment]
I feel the use of the `index` type makes all of it a bit more readable,
even though I do bump into issues from time to time having to cast into `string` for doing simple operations.

I don't think I will change this in this particular project, but will keep that in mind in the future.
